PREFIX ns1: <http://sw-portal.deri.org/ontologies/swportal#>
PREFIX entry: <http://fr.dbpedia.org/resource/>
PREFIX nas: <https://data.nasa.gov/ontologies/atmonto/NAS#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX dbo: <http://dbpedia.org/ontology/>

#Lister tous les aéroports dans un pays donné
SELECT ?name ?city ?iata ?icao
WHERE {
  ?airport ns1:inCountry dbres:France ;
           ns1:inCity ?city .
}



ORDER BY DESC(?count)

#Trouver les aéroports situés à une certaine altitude (au-dessus de 500 mètres)
SELECT ?name ?city ?country ?altitude
WHERE {
  ?airport dbo:altitude ?altitude ;
           ns1:Name ?name ;
           ns1:inCity ?city ;
           ns1:inCountry ?country .
  FILTER(?altitude > 500)
}
ORDER BY DESC(?altitude)


#trouver un aeroport a partir de la lonitude latittude( autour de 48.85, 2.35 pour Paris )
SELECT ?name ?city ?latitude ?longitude
WHERE {
  ?airport geo:lat ?latitude ;
           geo:long ?longitude ;
           ns1:Name ?name ;
           ns1:inCity ?city .
  FILTER(ABS(?latitude - 48.85) < 0.5 && ABS(?longitude - 2.35) < 0.5)
}

# compter le nombre d'aeroport par pays
SELECT ?country (COUNT(?airport) AS ?count)
WHERE {
  ?airport ns1:inCountry ?country .
}
GROUP BY ?country
ORDER BY DESC(?count)

# aeroport avec un fu cert fuseau horraire (ex :1)
SELECT ?name ?city ?country ?timezone
WHERE {
  ?airport tr:timezone "+1" ;
           ns1:Name ?name ;
           ns1:inCity ?city ;
           ns1:inCountry ?country .
}

# requete a venir avec jointures des dataset 
# compter le nombre d'accidents qui se produisent à proximité de chaque aéroport.
# Lister les détails des accidents associés à un aéroport spécifique
# Lister les aéroports et les conditions météorologiques des accidents à proximité



